name: ci

on:
  push:
    branches:
      - 'main'

jobs:
  docker:
    env:
      SOPS_VERSION: 3.7.0
    runs-on: ubuntu-latest
    steps:
      -
        name: Set up QEMU
        uses: docker/setup-qemu-action@v1
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      -
        name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Prepare build arhs
        run: |
          echo "docker_tag=`git rev-parse --abbrev-ref HEAD`" >> $GITHUB_ENV && \
          echo "vsc_ref=`git rev-parse --short HEAD`" >> $GITHUB_ENV && \
          echo "build_date=`date -u +'%Y-%m-%dT%H:%M:%SZ'`" >> $GITHUB_ENV
      -
        name: Build and push
        id: docker_build
        uses: docker/build-push-action@v2
        with:
          push: true
          build-args: |
            DOCKER_TAG=${{ env.docker_tag }}
            VCS_REF=${{ env.vsc_ref }}
            BUILD_DATE=${{ env.build_date }}
            SOPS_VERSION=${{ env.SOPS_VERSION }}
          tags: dteamdev/helm-secrets:${{ env.docker_tag }}
      -
        name: Image digest
        run: echo ${{ steps.docker_build.outputs.digest }}